//
// File generated by rootcint at Sun Sep 25 14:55:48 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME EURICADictionary
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EURICADictionary.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EURICAHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EURICAHit(void *p = 0);
   static void *newArray_EURICAHit(Long_t size, void *p);
   static void delete_EURICAHit(void *p);
   static void deleteArray_EURICAHit(void *p);
   static void destruct_EURICAHit(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EURICAHit*)
   {
      ::EURICAHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EURICAHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EURICAHit", ::EURICAHit::Class_Version(), "./EURICA.h", 17,
                  typeid(::EURICAHit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EURICAHit::Dictionary, isa_proxy, 4,
                  sizeof(::EURICAHit) );
      instance.SetNew(&new_EURICAHit);
      instance.SetNewArray(&newArray_EURICAHit);
      instance.SetDelete(&delete_EURICAHit);
      instance.SetDeleteArray(&deleteArray_EURICAHit);
      instance.SetDestructor(&destruct_EURICAHit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EURICAHit*)
   {
      return GenerateInitInstanceLocal((::EURICAHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EURICAHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void EURICA_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EURICA(void *p = 0);
   static void *newArray_EURICA(Long_t size, void *p);
   static void delete_EURICA(void *p);
   static void deleteArray_EURICA(void *p);
   static void destruct_EURICA(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EURICA*)
   {
      ::EURICA *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EURICA >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EURICA", ::EURICA::Class_Version(), "./EURICA.h", 115,
                  typeid(::EURICA), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EURICA::Dictionary, isa_proxy, 4,
                  sizeof(::EURICA) );
      instance.SetNew(&new_EURICA);
      instance.SetNewArray(&newArray_EURICA);
      instance.SetDelete(&delete_EURICA);
      instance.SetDeleteArray(&deleteArray_EURICA);
      instance.SetDestructor(&destruct_EURICA);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EURICA*)
   {
      return GenerateInitInstanceLocal((::EURICA*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EURICA*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr EURICAHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EURICAHit::Class_Name()
{
   return "EURICAHit";
}

//______________________________________________________________________________
const char *EURICAHit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EURICAHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EURICAHit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EURICAHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EURICAHit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EURICAHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EURICAHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EURICAHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr EURICA::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EURICA::Class_Name()
{
   return "EURICA";
}

//______________________________________________________________________________
const char *EURICA::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EURICA*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EURICA::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EURICA*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EURICA::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EURICA*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EURICA::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EURICA*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EURICAHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class EURICAHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(EURICAHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(EURICAHit::Class(),this);
   }
}

//______________________________________________________________________________
void EURICAHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EURICAHit.
      TClass *R__cl = ::EURICAHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fID", &fID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fen", &fen);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ftime", &ftime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fts", &fts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fadc", &fadc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ftdc", &ftdc);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhitsadded", &fhitsadded);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EURICAHit(void *p) {
      return  p ? new(p) ::EURICAHit : new ::EURICAHit;
   }
   static void *newArray_EURICAHit(Long_t nElements, void *p) {
      return p ? new(p) ::EURICAHit[nElements] : new ::EURICAHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_EURICAHit(void *p) {
      delete ((::EURICAHit*)p);
   }
   static void deleteArray_EURICAHit(void *p) {
      delete [] ((::EURICAHit*)p);
   }
   static void destruct_EURICAHit(void *p) {
      typedef ::EURICAHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::EURICAHit

//______________________________________________________________________________
void EURICA::Streamer(TBuffer &R__b)
{
   // Stream an object of class EURICA.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(EURICA::Class(),this);
   } else {
      R__b.WriteClassBuffer(EURICA::Class(),this);
   }
}

//______________________________________________________________________________
void EURICA::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EURICA.
      TClass *R__cl = ::EURICA::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fmult", &fmult);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhits", (void*)&fhits);
      R__insp.InspectMember("vector<EURICAHit*>", (void*)&fhits, "fhits.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fmultAB", &fmultAB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhitsAB", (void*)&fhitsAB);
      R__insp.InspectMember("vector<EURICAHit*>", (void*)&fhitsAB, "fhitsAB.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EURICA(void *p) {
      return  p ? new(p) ::EURICA : new ::EURICA;
   }
   static void *newArray_EURICA(Long_t nElements, void *p) {
      return p ? new(p) ::EURICA[nElements] : new ::EURICA[nElements];
   }
   // Wrapper around operator delete
   static void delete_EURICA(void *p) {
      delete ((::EURICA*)p);
   }
   static void deleteArray_EURICA(void *p) {
      delete [] ((::EURICA*)p);
   }
   static void destruct_EURICA(void *p) {
      typedef ::EURICA current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::EURICA

namespace ROOTDict {
   void vectorlEEURICAHitmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEEURICAHitmUgR_Dictionary();
   static void *new_vectorlEEURICAHitmUgR(void *p = 0);
   static void *newArray_vectorlEEURICAHitmUgR(Long_t size, void *p);
   static void delete_vectorlEEURICAHitmUgR(void *p);
   static void deleteArray_vectorlEEURICAHitmUgR(void *p);
   static void destruct_vectorlEEURICAHitmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<EURICAHit*>*)
   {
      vector<EURICAHit*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<EURICAHit*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<EURICAHit*>", -2, "/home/phong/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<EURICAHit*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEEURICAHitmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<EURICAHit*>) );
      instance.SetNew(&new_vectorlEEURICAHitmUgR);
      instance.SetNewArray(&newArray_vectorlEEURICAHitmUgR);
      instance.SetDelete(&delete_vectorlEEURICAHitmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlEEURICAHitmUgR);
      instance.SetDestructor(&destruct_vectorlEEURICAHitmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<EURICAHit*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<EURICAHit*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEEURICAHitmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<EURICAHit*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEEURICAHitmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<EURICAHit*> : new vector<EURICAHit*>;
   }
   static void *newArray_vectorlEEURICAHitmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<EURICAHit*>[nElements] : new vector<EURICAHit*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEEURICAHitmUgR(void *p) {
      delete ((vector<EURICAHit*>*)p);
   }
   static void deleteArray_vectorlEEURICAHitmUgR(void *p) {
      delete [] ((vector<EURICAHit*>*)p);
   }
   static void destruct_vectorlEEURICAHitmUgR(void *p) {
      typedef vector<EURICAHit*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<EURICAHit*>

/********************************************************
* EURICADictionary.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEURICADictionary();

extern "C" void G__set_cpp_environmentEURICADictionary() {
  G__cpp_reset_tagtableEURICADictionary();
}
#include <new>
extern "C" int G__cpp_dllrevEURICADictionary() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EURICAHit */
static int G__EURICADictionary_221_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EURICAHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EURICAHit[n];
     } else {
       p = new((void*) gvp) EURICAHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EURICAHit;
     } else {
       p = new((void*) gvp) EURICAHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EURICAHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 5
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new EURICAHit(
(short) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (unsigned short) G__int(libp->para[3])
, (unsigned long long) G__ULonglong(libp->para[4]));
   } else {
     p = new((void*) gvp) EURICAHit(
(short) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (unsigned short) G__int(libp->para[3])
, (unsigned long long) G__ULonglong(libp->para[4]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetID((short) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetEnergy((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetTime((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetADC((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetTDC((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->SetTimestamp((unsigned long long) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->AddBackHit((EURICAHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((EURICAHit*) G__getstructoffset())->GetID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((EURICAHit*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((EURICAHit*) G__getstructoffset())->GetTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((EURICAHit*) G__getstructoffset())->GetTimestamp());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EURICAHit*) G__getstructoffset())->GetADC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EURICAHit*) G__getstructoffset())->GetTDC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((EURICAHit*) G__getstructoffset())->GetHitsAdded());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EURICAHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICAHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EURICAHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EURICAHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICAHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICAHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EURICAHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICAHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_221_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EURICAHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EURICADictionary_221_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EURICAHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EURICAHit(*(EURICAHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EURICAHit G__TEURICAHit;
static int G__EURICADictionary_221_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EURICAHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EURICAHit*) (soff+(sizeof(EURICAHit)*i)))->~G__TEURICAHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EURICAHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EURICAHit*) (soff))->~G__TEURICAHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EURICADictionary_221_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EURICAHit* dest = (EURICAHit*) G__getstructoffset();
   *dest = *(EURICAHit*) libp->para[0].ref;
   const EURICAHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* EURICA */
static int G__EURICADictionary_222_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EURICA* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EURICA[n];
     } else {
       p = new((void*) gvp) EURICA[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EURICA;
     } else {
       p = new((void*) gvp) EURICA;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->AddHit((EURICAHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->AddHitAB((EURICAHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->SetHits(*((vector<EURICAHit*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->SetABHits(*((vector<EURICAHit*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->AddHits(*((vector<EURICAHit*>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((EURICA*) G__getstructoffset())->GetMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<EURICAHit*>* pobj;
         vector<EURICAHit*> xobj = ((EURICA*) G__getstructoffset())->GetHits();
         pobj = new vector<EURICAHit*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EURICA*) G__getstructoffset())->GetHit((unsigned short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EURICA*) G__getstructoffset())->GetMultAB());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<EURICAHit*>* pobj;
         vector<EURICAHit*> xobj = ((EURICA*) G__getstructoffset())->GetHitsAB();
         pobj = new vector<EURICAHit*>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((EURICA*) G__getstructoffset())->GetHitAB((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EURICA::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICA::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EURICA::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EURICA::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EURICA*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICA::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EURICA::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EURICA::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EURICADictionary_222_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EURICA::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EURICADictionary_222_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EURICA* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EURICA(*(EURICA*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EURICA G__TEURICA;
static int G__EURICADictionary_222_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EURICA*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EURICA*) (soff+(sizeof(EURICA)*i)))->~G__TEURICA();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EURICA*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EURICA*) (soff))->~G__TEURICA();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EURICADictionary_222_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EURICA* dest = (EURICA*) G__getstructoffset();
   *dest = *(EURICA*) libp->para[0].ref;
   const EURICA& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EURICAHit */

/* EURICA */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEURICADictionary {
 public:
  G__Sizep2memfuncEURICADictionary(): p(&G__Sizep2memfuncEURICADictionary::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEURICADictionary::*p)();
};

size_t G__get_sizep2memfuncEURICADictionary()
{
  G__Sizep2memfuncEURICADictionary a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEURICADictionary() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit))) {
     EURICAHit *G__Lderived;
     G__Lderived=(EURICAHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit),G__get_linked_tagnum(&G__EURICADictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA))) {
     EURICA *G__Lderived;
     G__Lderived=(EURICA*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA),G__get_linked_tagnum(&G__EURICADictionaryLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEURICADictionary() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<EURICAHit*>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EURICAHit */
static void G__setup_memvarEURICAHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit));
   { EURICAHit *p; p=(EURICAHit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,115,0,0,-1,-1,-1,2,"fID=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"fen=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"ftime=",0,(char*)NULL);
   G__memvar_setup((void*)0,109,0,0,-1,-1,-1,2,"fts=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"fadc=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"ftdc=",0,(char*)NULL);
   G__memvar_setup((void*)0,114,0,0,-1,-1,-1,2,"fhitsadded=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EURICADictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* EURICA */
static void G__setup_memvarEURICA(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA));
   { EURICA *p; p=(EURICA*)0x1000; if (p) { }
   G__memvar_setup((void*)0,114,0,0,-1,-1,-1,2,"fmult=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR),G__defined_typename("vector<EURICAHit*>"),-1,2,"fhits=",0,(char*)NULL);
   G__memvar_setup((void*)0,114,0,0,-1,-1,-1,2,"fmultAB=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR),G__defined_typename("vector<EURICAHit*>"),-1,2,"fhitsAB=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__EURICADictionaryLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEURICADictionary() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEURICAHit(void) {
   /* EURICAHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit));
   G__memfunc_setup("EURICAHit",734,G__EURICADictionary_221_0_1, 105, G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EURICAHit",734,G__EURICADictionary_221_0_2, 105, G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 0, 5, 1, 1, 0, 
"s - - 0 - id d - - 0 - en "
"d - - 0 - time r - - 0 - hitsadded "
"m - - 0 - ts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetID",441,G__EURICADictionary_221_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "s - - 0 - id", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__EURICADictionary_221_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - energy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__EURICADictionary_221_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetADC",500,G__EURICADictionary_221_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - adc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTDC",519,G__EURICADictionary_221_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - tdc", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestamp",1248,G__EURICADictionary_221_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "m - - 0 - ts", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddBackHit",927,G__EURICADictionary_221_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "U 'EURICAHit' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetID",429,G__EURICADictionary_221_0_11, 115, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__EURICADictionary_221_0_12, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTime",687,G__EURICADictionary_221_0_13, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestamp",1236,G__EURICADictionary_221_0_14, 109, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetADC",488,G__EURICADictionary_221_0_15, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTDC",507,G__EURICADictionary_221_0_16, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitsAdded",1162,G__EURICADictionary_221_0_17, 114, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__EURICADictionary_221_0_19, 85, G__get_linked_tagnum(&G__EURICADictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EURICAHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EURICADictionary_221_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICAHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EURICADictionary_221_0_21, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EURICAHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EURICADictionary_221_0_22, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EURICAHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EURICADictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EURICADictionary_221_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EURICADictionary_221_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICAHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EURICADictionary_221_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EURICAHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EURICADictionary_221_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICAHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EURICADictionary_221_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EURICAHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EURICAHit", 734, G__EURICADictionary_221_0_31, (int) ('i'), G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 0, 1, 1, 1, 0, "u 'EURICAHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EURICAHit", 860, G__EURICADictionary_221_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EURICADictionary_221_0_33, (int) ('u'), G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 1, 1, 1, 1, 0, "u 'EURICAHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncEURICA(void) {
   /* EURICA */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA));
   G__memfunc_setup("EURICA",441,G__EURICADictionary_222_0_1, 105, G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("AddHit",558,G__EURICADictionary_222_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'EURICAHit' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHitAB",689,G__EURICADictionary_222_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "U 'EURICAHit' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHits",708,G__EURICADictionary_222_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<EURICAHit*,allocator<EURICAHit*> >' 'vector<EURICAHit*>' 0 - hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetABHits",839,G__EURICADictionary_222_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<EURICAHit*,allocator<EURICAHit*> >' 'vector<EURICAHit*>' 0 - hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHits",673,G__EURICADictionary_222_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<EURICAHit*,allocator<EURICAHit*> >' 'vector<EURICAHit*>' 0 - hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMult",706,G__EURICADictionary_222_0_8, 114, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHits",696,G__EURICADictionary_222_0_9, 117, G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR), G__defined_typename("vector<EURICAHit*>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHit",581,G__EURICADictionary_222_0_10, 85, G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 0, 1, 1, 1, 0, "r - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMultAB",837,G__EURICADictionary_222_0_11, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitsAB",827,G__EURICADictionary_222_0_12, 117, G__get_linked_tagnum(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR), G__defined_typename("vector<EURICAHit*>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHitAB",712,G__EURICADictionary_222_0_13, 85, G__get_linked_tagnum(&G__EURICADictionaryLN_EURICAHit), -1, 0, 1, 1, 1, 0, "i - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "C - 'Option_t' 10 '\"\"' option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__EURICADictionary_222_0_15, 85, G__get_linked_tagnum(&G__EURICADictionaryLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EURICA::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__EURICADictionary_222_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICA::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__EURICADictionary_222_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EURICA::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__EURICADictionary_222_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EURICA::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__EURICADictionaryLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__EURICADictionary_222_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__EURICADictionary_222_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICA::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__EURICADictionary_222_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EURICA::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__EURICADictionary_222_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EURICA::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__EURICADictionary_222_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EURICA::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EURICA", 441, G__EURICADictionary_222_0_27, (int) ('i'), G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA), -1, 0, 1, 1, 1, 0, "u 'EURICA' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EURICA", 567, G__EURICADictionary_222_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EURICADictionary_222_0_29, (int) ('u'), G__get_linked_tagnum(&G__EURICADictionaryLN_EURICA), -1, 1, 1, 1, 1, 0, "u 'EURICA' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEURICADictionary() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEURICADictionary() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEURICADictionary() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EURICADictionaryLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_EURICAHit = { "EURICAHit" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_EURICA = { "EURICA" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR = { "vector<EURICAHit*,allocator<EURICAHit*> >" , 99 , -1 };
G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<EURICAHit*,allocator<EURICAHit*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEURICADictionary() {
  G__EURICADictionaryLN_TClass.tagnum = -1 ;
  G__EURICADictionaryLN_TBuffer.tagnum = -1 ;
  G__EURICADictionaryLN_TMemberInspector.tagnum = -1 ;
  G__EURICADictionaryLN_TObject.tagnum = -1 ;
  G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__EURICADictionaryLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__EURICADictionaryLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__EURICADictionaryLN_EURICAHit.tagnum = -1 ;
  G__EURICADictionaryLN_EURICA.tagnum = -1 ;
  G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR.tagnum = -1 ;
  G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEURICADictionary() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TClass);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TObject);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_EURICAHit),sizeof(EURICAHit),-1,323840,(char*)NULL,G__setup_memvarEURICAHit,G__setup_memfuncEURICAHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_EURICA),sizeof(EURICA),-1,291072,(char*)NULL,G__setup_memvarEURICA,G__setup_memfuncEURICA);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupEURICADictionary(void) {
  G__check_setup_version(30051515,"G__cpp_setupEURICADictionary()");
  G__set_cpp_environmentEURICADictionary();
  G__cpp_setup_tagtableEURICADictionary();

  G__cpp_setup_inheritanceEURICADictionary();

  G__cpp_setup_typetableEURICADictionary();

  G__cpp_setup_memvarEURICADictionary();

  G__cpp_setup_memfuncEURICADictionary();
  G__cpp_setup_globalEURICADictionary();
  G__cpp_setup_funcEURICADictionary();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEURICADictionary();
  return;
}
class G__cpp_setup_initEURICADictionary {
  public:
    G__cpp_setup_initEURICADictionary() { G__add_setup_func("EURICADictionary",(G__incsetup)(&G__cpp_setupEURICADictionary)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEURICADictionary() { G__remove_setup_func("EURICADictionary"); }
};
G__cpp_setup_initEURICADictionary G__cpp_setup_initializerEURICADictionary;

