/********************************************************************
* EURICADictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EURICADictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEURICADictionary();
extern void G__cpp_setup_inheritanceEURICADictionary();
extern void G__cpp_setup_typetableEURICADictionary();
extern void G__cpp_setup_memvarEURICADictionary();
extern void G__cpp_setup_globalEURICADictionary();
extern void G__cpp_setup_memfuncEURICADictionary();
extern void G__cpp_setup_funcEURICADictionary();
extern void G__set_cpp_environmentEURICADictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EURICA.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EURICADictionaryLN_TClass;
extern G__linked_taginfo G__EURICADictionaryLN_TBuffer;
extern G__linked_taginfo G__EURICADictionaryLN_TMemberInspector;
extern G__linked_taginfo G__EURICADictionaryLN_TObject;
extern G__linked_taginfo G__EURICADictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EURICADictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__EURICADictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EURICADictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__EURICADictionaryLN_EURICAHit;
extern G__linked_taginfo G__EURICADictionaryLN_EURICA;
extern G__linked_taginfo G__EURICADictionaryLN_vectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgR;
extern G__linked_taginfo G__EURICADictionaryLN_reverse_iteratorlEvectorlEEURICAHitmUcOallocatorlEEURICAHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
